version: "3.8"
services:
  database:
    image: postgres:14-alpine # imagem a ser utilizada
    restart: always # reinicia automáticamente quando acontece algum erro
    environment: # o -e do docker run supracitado
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db_
    ports:
      - "5441:5432"
    volumes:
      - pg-db:/var/lib/postgresql/data
volumes:
  pg-db:
    driver: local
